<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QGMO3TS" failures="1" tests="9" name="testCases.AgentsTest" time="27.663" errors="0" timestamp="2025-06-23T20:56:12 IST" skipped="1">
  <testcase classname="testCases.AgentsTest" name="verifyPageIsAgentsPage" time="0.444"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNullAgentName" time="1.389"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNullAgentEmail" time="1.884"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNullAgentMobileNumber" time="2.569"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNullPassword" time="2.843"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNullConfirmPassword" time="3.147"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyDuplicateAgentCreationWithSameEmail" time="14.912">
    <failure message="The following asserts failed:
	Error message does not match! expected [Email already used] but found [Failed to add agent!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error message does not match! expected [Email already used] but found [Failed to add agent!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.AgentsTest.verifyDuplicateAgentCreationWithSameEmail(AgentsTest.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyDuplicateAgentCreationWithSameEmail -->
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifySearchByUserName" time="0.475"/>
  <system-out/>
  <testcase classname="testCases.AgentsTest" name="verifyNewAgentCreationWithValidData">
    <skipped/>
  </testcase> <!-- verifyNewAgentCreationWithValidData -->
  <system-out/>
</testsuite> <!-- testCases.AgentsTest -->
